### ISSUE TITLE
Should we link to articles like this?

### ISSUE THREAD

**Issue by jeremyheiler** [papers-we-love/papers-we-love#101]
http://web.archive.org/web/20111218093802/http://blog.objectmentor.com/articles/2009/02/26/10-papers-every-programmer-should-read-at-least-twice

http://blog.fogus.me/2011/09/08/10-technical-papers-every-programmer-should-read-at-least-twice/

re: https://twitter.com/fogus/status/454698907873054720

**Comment by AnneTheAgile** [comment]
One idea for adding more metadata regarding people's opinions of papers might be to organize it in a database, eg like [1] a small app that I learned about last year?
AnneTheAgile
 1.[] ; ; ; ; ; X.imalsogreg/reffit ; ; https://github.com/ImAlsoGreg/reffit
1.[] ; ; ; ; ; X.imalsogreg/reffit ; ; https://github.com/ImAlsoGreg/reffit

**Comment by samlecuyer** [comment]
I've actually got a running wishlist for the LA chapter, where I link to these.

http://cateches.is/papers-wishlist

**Comment by DarrenN** [comment]
Closed due to inactivity - reopen if this still needs to be addressed
