### ISSUE TITLE
PWL#7 => Armon Dadgar on SWIM

### ISSUE THREAD

**Issue by Randommood** [papers-we-love/papers-we-love#158]
[Armon Dadgar](https://twitter.com/armon) from [Hashicorp](http://www.hashicorp.com/) presents the  [SWIM: Scalable Weakly-consistent Infection-style Process Group Membership Protocol](http://www.cs.cornell.edu/~asdas/research/dsn02-swim.pdf)  paper by Abhinandan Das, Indranil Gupta, and Ashish Motivala.

Please offer up questions, comments, or additional information regarding this paper. For this particular meetup we will try a round of moderated discussions. Pre-submit any topics in this thread.

The meetup is scheduled for Thursday, September 25, 2014 @ 6:30pm  - RSVP here > http://www.meetup.com/papers-we-love-too/events/176288712/

**Comment by Gerold103** [comment]
The paper link is 404.[
[SWIM.pdf](https://github.com/papers-we-love/papers-we-love/files/3220392/SWIM.pdf)
](url)
