### ISSUE TITLE
CS education and pedagogy folder

### ISSUE THREAD

**Issue by ashleygwilliams** [papers-we-love/papers-we-love#167]
i'd like to propose an education folder. spoke briefly with @videlalvaro in IRC and he suggested the [comp_sci_fundamentals_and_history](https://github.com/papers-we-love/papers-we-love/tree/master/comp_sci_fundamentals_and_history) folder but the papers i am considering are neither fundamentals or history, which i think would make their discovery difficult if they were put in that category. additionally spoke to @zeeshanlakhani who said that there are education papers in the repo already- though, to me at least, it is unclear where they are, so if we did make new category, i'd be happy to volunteer seeking those out and moving them.

totally understand the desire to keep the categories limited, but i think this is an important and distinct one.

example papers: 

- http://www.info.ucl.ac.be/~pvr/fdpefinalweb.pdf
- http://dl.acm.org/citation.cfm?id=1733912

**Comment by DarrenN** [comment]
Closed due to inactivity
