### ISSUE TITLE
PWLSF#10 => Peter Bailis on Managing Update Conflicts in Bayou, A Weakly Connected Replicated Storage System

### ISSUE THREAD

**Issue by Randommood** [papers-we-love/papers-we-love#193]
Peter Bailis presents the "Managing Update Conflicts in Bayou, A Weakly Connected Replicated Storage System" paper by Doug Terry, Marvin Theimer, Karin Petersen, Alan J. Demers, Mike J. Spreitzer, and Carl H. Hauser in SOSP 1995. http://db.cs.berkeley.edu/cs286/papers/bayou-sosp1995.pdf

Peter tells us: "A perennial challenge in managing shared, mutable state in distributed systems is the ability to permit concurrent writes while maintaining some degree of application "correctness." Bayou is an excellent and early example of an "optimistic" strategy for handling the concurrent update problem. Many of the techniques in Bayou---such as dependency tracking, application-specific merge procedures, and log shipping---are increasingly popular, can be found in systems like Dynamo, and help understand when and why mechanisms like CRDTs are useful."

Please offer up questions, comments, or additional information regarding this paper. For this particular meetup we will try a round of moderated discussions. Pre-submit any topics in this thread.

This meetup will happen on **Wednesday, December 17, 2014** @ Fastly HQ - RSVP information here: http://www.meetup.com/papers-we-love-too/events/197678922/

**Comment by Randommood** [comment]
Peter's slides and video are up!
* https://speakerdeck.com/paperswelove/pwl-number-10-equals-peter-bailis-on-managing-update-conflicts-in-bayou
* https://www.youtube.com/watch?v=tg7zvyWm_NE&feature=youtu.be

**Comment by tejas-2232** [comment]
Hey @Randommood ,
Thank you for putting it here. But I'm not able to access the Slides 😭 
can you please check it again

**Comment by tejas-2232** [comment]
> Hey @Randommood , Thank you for putting it here. But I'm not able to access the Slides 😭 can you please check it again

Please bring back the slides....They are awesome 💯
