### ISSUE TITLE
PWLSF#11 => Alex Rasmussen on Flat Datacenter Storage

### ISSUE THREAD

**Issue by Randommood** [papers-we-love/papers-we-love#198]
Alex Rasmussen presents the "Flat Datacenter Storage" paper by Edmund B. Nightingale, Jeremy Elson,Jinliang Fan, Owen Hofmann∗, Jon Howell, and Yutaka Suzue http://css.csail.mit.edu/6.824/2014/papers/fds.pdf. 

Alex tells us: " Flat Datacenter Storage (FDS) is, as the intro describes, "a high-performance, fault-tolerant, large-scale, locality-oblivious blob store". It's also a great example of how carefully thought-out co-design of software and hardware for a target workload can yield really impressive performance results, even in the presence of heterogeneity and operating at scale. In my (admittedly biased) opinion, this style of system design doesn't get enough attention outside of academia, and has a lot to teach us about how data-intensive systems should be designed."

Please offer up questions, comments, or additional information regarding this paper. For this particular meetup we will try a round of moderated discussions. Pre-submit any topics in this thread.

This meetup will happen on Thursday, January 22, 2015 @ Fastly HQ - RSVP information here: http://www.meetup.com/papers-we-love-too/events/212582062/

**Comment by ejgreenberg** [comment]
Reminder: this will be at Github, not Fastly this month!
