### ISSUE TITLE
Writing script for name-cleanup and title from pdf if possible

### ISSUE THREAD

**Issue by zeeshanlakhani** [papers-we-love/papers-we-love#20]
References the conversation from https://github.com/papers-we-love/papers-we-love/pull/18#commitcomment-5571903.

**Comment by Khalian** [comment]
Is this what you are talking about as a script? (I did not include exception handling because I wanted to confirm the base logic first). 

```
#!/usr/bin/env python
from os import rename
import re

def cleanup_filename(filename):
    filename_without_spaces = re.sub('\s+', '-', filename)
    filename_cleanedup = filename_without_spaces.lower()
    rename(filename, filename_cleanedup)

```

**Comment by DarrenN** [comment]
@Khalian that pretty much does it as far as normalizing the filename. I think @zeeshanlakhani was looking for something that could also rename the file according to the paper title (see #310) but I'll let him speak to that.

**Comment by niudage** [comment]
thankyou
