### ISSUE TITLE
Papers We Love #12 - Andrew Turley on Incremental Mature Garbage Collection Using the Train Algorithm

### ISSUE THREAD

**Issue by zeeshanlakhani** [papers-we-love/papers-we-love#258]
- @aturley 
- [meetup](http://www.meetup.com/papers-we-love/events/219423215/)

*Sponsored By*

- [TwoSigma](https://www.twosigma.com/)
![twosigma_rgb](https://cloud.githubusercontent.com/assets/202820/6004990/c9be60f2-aabb-11e4-97ca-e4543aabc6e6.jpg)

- [The Ladders](https://www.theladders.com/) ([@TheLaddersDev](https://twitter.com/theladdersdev))
![The Ladders](https://cloud.githubusercontent.com/assets/202820/5038556/feaf396c-6b5f-11e4-8f11-96418f99d0f1.png)

- [Tumblr](https://www.tumblr.com/)
![600_433118808](https://cloud.githubusercontent.com/assets/202820/6473811/d24f23d0-c1c9-11e4-8330-a33897e25818.jpeg)

This issue has been created to start/spark/organize a conversation on the paper **Incremental Mature Garbage Collection Using the Train Algorithm** by Jacob Seligmann & Steffen Grarup.

Please offer up questions, comments, or additional information regarding this paper.

Paper can be found [here](https://www.sics.se/~seif/DatalogiII/Book/train.ps) or in the [repo](https://github.com/papers-we-love/papers-we-love/blob/master/garbage_collection/incremental_mature_garbage_collection_using_the_train_algorithm.pdf).

**Description**

Automatic garbage collection has spared programmers from an entire class of programming errors related to memory leaks and attempting to access objects that were incorrectly freed. As programs have grown in size and complexity, so have the systems that manage garbage collection. Each algorithm makes a different set of tradeoffs between factors such as the space used by objects, the space used by bookkeeping, the number of unused objects (garbage) that remain uncollected, the time spent in allocation, and the time spent in
collection.

The Train Algorithm is an incremental generational garbage collector that was designed to deal with the long and unpredictable pause times caused by other algorithms. It does this by grouping objects together on "cars" in "trains". The algorithm provides a strategy for moving objects from the younger generation into different cars, moving objects from one car to another, and collecting cars and trains. It was first described by Hudson and Moss in the paper "Incremental
Collection of Mature Objects".

In their paper "Incremental Mature Garbage Collection Using the TrainAlgorithm," Seligmann and Grarup describe what they believe is the first implementation of the Train Algorithm, which they used to replace the traditional mark-and-sweep collector that was used in the BETA programming language. They discuss their implementation and present information about the performance characteristics of the new algorithm as compared to the original.

**Bio**

Andrew Turley ([@casio_juarez](https://twitter.com/casio_juarez)) is a lead software engineer on the platform team at [TheLadders](https://www.theladders.com/), where he builds infrastructure by linking Storm topologies together using RabbitMQ. He has also had numerous professional brushes with lower levels of the software stack, including building embedded systems for processing audio at DigiDesign, and helping to improve the performance of iOS at Apple.

**Comment by NewAlexandria** [comment]
Is there a good paper that I can point people toward, to get an overview of the major concepts in GC (even where maybe all such elements are not used in every GC strategy)?  [The wiki article](http://en.wikipedia.org/wiki/Garbage_collection_%28computer_science%29) is a good starting point, IMO, for conceptual breadth.

**Comment by aturley** [comment]
The [first Papers We Love NYC meetup](http://www.meetup.com/papers-we-love/events/163406212/) covered ["A Uniﬁed Theory of Garbage Collection"](http://www.cs.virginia.edu/~cs415/reading/bacon-garbage.pdf), which provides a good overview of the various algorithms. You can also [watch](https://www.youtube.com/watch?v=XtUtfARSIv8) the talk.
