### ISSUE TITLE
Categorize Distributed Systems Papers' Folder into focused, sub-categories.

### ISSUE THREAD

**Issue by zeeshanlakhani** [papers-we-love/papers-we-love#260]
Any volunteers? :hamburger:

**Comment by JamesWKerr** [comment]
p2p(3 generations)
San
Enumeration/host discovery
Dhthe

State
Logically centralised physically distributed?
I could make an attempt

I could

**Comment by DarrenN** [comment]
@JamesWKerr - Pull Requests welcome

**Comment by NewAlexandria** [comment]
Per my comment on #339:

Some look like they are better suited as networking topic (e.g. maybe the Tor paper).

We can relocate papers and make links out to where they are located, perhaps in an 'appendix' section of the README.

Thoughts?

**Comment by jeremyheiler** [comment]
For the appendix, do you mean links to the papers, or links to the relevant topic directories?

**Comment by NewAlexandria** [comment]
@jeremyheiler PR #343 is a demo of what I mean.
