### ISSUE TITLE
Papers We Love #14 - John Myles White on Fundamental Concepts in Programming Languages

### ISSUE THREAD

**Issue by zeeshanlakhani** [papers-we-love/papers-we-love#286]
- @johnmyleswhite
- [meetup](http://www.meetup.com/papers-we-love/events/220081725)

*Sponsored By*

- [TwoSigma](https://www.twosigma.com/)
![twosigma_rgb](https://cloud.githubusercontent.com/assets/202820/6004990/c9be60f2-aabb-11e4-97ca-e4543aabc6e6.jpg)

- [The Ladders](https://www.theladders.com/) ([@TheLaddersDev](https://twitter.com/theladdersdev))
![The Ladders](https://cloud.githubusercontent.com/assets/202820/5038556/feaf396c-6b5f-11e4-8f11-96418f99d0f1.png)

- [Tumblr](https://www.tumblr.com/)
![600_433118808](https://cloud.githubusercontent.com/assets/202820/6473811/d24f23d0-c1c9-11e4-8330-a33897e25818.jpeg)

This issue has been created to start/spark/organize a conversation on the paper **Fundamental Concepts in Programming Languages** by Christopher Strachey.

Please offer up questions, comments, or additional information regarding this paper.

Paper can be found [here](http://www.cs.cmu.edu/~crary/819-f09/Strachey67.pdf) or in the [repo](https://github.com/papers-we-love/papers-we-love/blob/master/plt/fundamental-concepts-in-programming-languages.pdf).

**Description**

Strachey's lectures on "Fundamental Concepts in Programming Languages" provided an extremely broad survey of core issues in programming language design that provided much of the terminology we use today, including definitions of the kinds of polymorphism and the kinds of expressions we see in programming languages. Published as a paper many years later, Strachey's lectures provide an especially readable overview of programming languages concepts.

**Bio**

John Myles White ([@johnmyleswhite](https://twitter.com/johnmyleswhite)) is a Julia hacker who loves thinking about the ways in which the design of technical programming languages influences the way in which we think about statistics and machine learning. He's written two books about machine learning for O'Reilly and works at Facebook.

**Comment by MonsieurCactus** [comment]
I am guessing you mean the second one:

> This issue has been created to start/spark/organize a conversation on the paper Incremental Mature Garbage Collection Using the Train Algorithm by Jacob Seligmann & Steffen Grarup.
>
> ...
> This issue has been created to start/spark/organize a conversation on the paper Fundamental Concepts in Programming Languages by Christopher Strachey.

**Comment by zeeshanlakhani** [comment]
@MonsieurCactus thank you, my apologies :).
