### ISSUE TITLE
Should we add a year next to the title?

### ISSUE THREAD

**Issue by inputsh** [papers-we-love/papers-we-love#290]
I think that it is important to add a year of the publication next to the title. 

The reason for this issue is because it can make a lot of difference when the reader is deciding on what to read. He might be interested to learn something brand new, or he might be interested to read a paper that made an impact on the past.

Adding these information would help the readers out a lot.

**Comment by darthdeus** [comment]
+1

**Comment by JKereliuk** [comment]
+1

**Comment by DarrenN** [comment]
Makes sense, @aleksandar-todorovic @darthdeus @JKereliuk - Pull Requests welcome.

**Comment by jeremyheiler** [comment]
This could be automatically done if we pull metadata from an external system.

https://github.com/papers-we-love/papers-we-love/issues/374

**Comment by koconder** [comment]
+1

**Comment by emreakay** [comment]
+2

**Comment by emreakay** [comment]
+1
