### ISSUE TITLE
Papers We Love #15 - Neha Narula on The Scalable Commutativity Rule

### ISSUE THREAD

**Issue by zeeshanlakhani** [papers-we-love/papers-we-love#291]
- @narula
- [meetup](http://www.meetup.com/papers-we-love/events/221194444/)

*Sponsored By*

[![twosigma_rgb](https://cloud.githubusercontent.com/assets/202820/6004990/c9be60f2-aabb-11e4-97ca-e4543aabc6e6.jpg)](https://www.twosigma.com/)

[![600_435437715](https://cloud.githubusercontent.com/assets/202820/6790038/23891c7c-d17b-11e4-9f6b-852a5570b3d9.jpeg)](https://www.dropbox.com/)

[![600_433118808](https://cloud.githubusercontent.com/assets/202820/6473811/d24f23d0-c1c9-11e4-8330-a33897e25818.jpeg)](https://www.tumblr.com/_)

This issue has been created to start/spark/organize a conversation on the paper **The Scalable Commutativity Rule: Designing Scalable Software for Multicore Processors** by Clements, Kaashoek, Zeldovich, Morris, and Kohler.

Please offer up questions, comments, or additional information regarding this paper.

Paper can be found [here](http://web.mit.edu/amdragon/www/pubs/commutativity-sosp13.pdf).

## Description

Moore's law is over, or at least, we won't be making programs go faster by running on faster processors, but instead by parallelizing our code to use more of them.  Reasoning about concurrent code is difficult; but it's also very hard to understand whether your design has latent scalability bottlenecks until you can actually run it on many cores.  And what if the problem is in your interface, instead of just the implementation?

This paper presents a simple, elegant rule:  whenever interface operations commute, they can be implemented in a way that scales.  

The authors apply this idea to Linux, and create a new operating system by using the rule, sv6.  Their paper also comes with software, [COMMUTER](http://pdos.csail.mit.edu/commuter/), which can help developers evaluate their interfaces to find opportunities for scaling.

This is a very powerful idea, and probably has applications in other areas like distributed systems. In this talk I'll present the paper, and speculate a bit about where else this research could be useful.

## Bio

Neha Narula ([@neha](https://twitter.com/neha)) is a PhD candidate at MIT building fast, scalable distributed systems. In a previous life she was a Senior Software Engineer at Google, where she designed the first version of Blobstore, a system for storing and serving petabytes of immutable data, and worked on Native Client, a system for running native code securely through the browser.

**Comment by mrallen1** [comment]
Wish I could be there! Hope there is a recording.
