### ISSUE TITLE
Papers We Love #16 - Samy Al Bahra on Making Lockless Synchronization Fast

### ISSUE THREAD

**Issue by zeeshanlakhani** [papers-we-love/papers-we-love#301]
@sbahra
- [meetup](http://www.meetup.com/papers-we-love/events/222366060/)

*Sponsored By*

[![twosigma_rgb](https://cloud.githubusercontent.com/assets/202820/6004990/c9be60f2-aabb-11e4-97ca-e4543aabc6e6.jpg)](https://www.twosigma.com/)

[![The Ladders](https://cloud.githubusercontent.com/assets/202820/5038556/feaf396c-6b5f-11e4-8f11-96418f99d0f1.png)](https://twitter.com/theladdersdev)

[![600_433118808](https://cloud.githubusercontent.com/assets/202820/6473811/d24f23d0-c1c9-11e4-8330-a33897e25818.jpeg)](https://www.tumblr.com/_)

This issue has been created to start/spark/organize a conversation on the paper **Making Lockless Synchronization Fast: Performance Implications of Memory Reclamation** by Hart, McKenney, and Brown. 

Please offer up questions, comments, or additional information regarding this paper.

Paper can be found [here](http://www.rdrop.com/users/paulmck/RCU/hart_ipdps06.pdf) or in the [repo](https://github.com/papers-we-love/papers-we-love/blob/master/memory_reclamation/making-lockless-synchronization-fast.pdf).

## Description

Multicore systems are ubiquitous but modern concurrent programming techniques still do not see wide-spread adoption. Most concurrent software (developed in low-level languages) still relies on error-prone and unscalable memory management techniques for correctness despite the introduction of superior methods over 30 years ago. Safe memory reclamation allows for performant and robust memory management that is also suitable for advanced concurrent programming techniques such as non-blocking synchronization. If properly used, safe memory reclamation techniques allow improved performance and simplicity without the complexity of full-blown garbage collection.

This paper provides a terrific overview of common safe memory reclamation mechanisms and then explores their performance implications. In this talk, I will do the same but with stronger emphasis on the introductory aspects of safe memory reclamation and contrast with a refreshed performance analysis.

## Bio

Samy Al Bahra ([@0xf390](https://twitter.com/0xf390)) is the co-founder of Backtrace, where he is helping build a modern debugging platform for today's complex applications. Prior to Backtrace, Samy was a principal engineer at AppNexus, where he played a lead role in the architecture and development of many mission-critical components of the ecosystem. His work at AppNexus was instrumental in scaling the system to 18 billion impressions with orders of magnitude in efficiency improvements. Prior to AppNexus, Samy was behind major performance improvements to the core technology at Message Systems. At the George Washington University High Performance Computing Laboratory, Samy worked on the UPC programming language, heterogeneous computing and multicore synchronization. Samy is also the founder of the Concurrency Kit project, which several leading technology companies rely on for scalability and performance. Samy serves on the ACM Practitioners Board.

**Comment by sbahra** [comment]
:]
