### ISSUE TITLE
A list of recently added papers

### ISSUE THREAD

**Issue by nogweii** [papers-we-love/papers-we-love#310]
Not to be confused with recently published papers, but a list of say, the 10 most recently added papers to this repository, regardless of when they were published. I visit the website occasionally, but don't really have a good idea as to which papers were recently found.

**Comment by aleksandar-todorovic** [comment]
Sounds like a nice idea!

**Comment by gfixler** [comment]
If you have the repo locally, you can always do this in the shell to see the 10 most recently added, non-README.md files:

    $ git log --name-status | \grep "^A\s" | grep -v README\.md | head

At the moment, I get this output (newest at the top):

    A       memory_reclamation/making-lockless-synchronization-fast.pdf
    A       distributed_systems/join-calculus.pdf
    A       pattern_matching/aho-corasick-string-matching.pdf
    A       plt/composable-and-compilable-macros-you-want-it-when.pdf
    A       garbage_collection/the_lisp_ii_garbage_collector.pdf
    A       cryptography/communication-theory-of-secrecy-systems.pdf
    A       cryptography/a-mathematical-theory-of-cryptography-shannon.pdf
    A       smalltalk/Design-Principles-Behind-Smalltalk.pdf
    A       smalltalk/Design-Principles-Behind-Smalltalk.pdf
    A       historical/smalltalk/The-Early-History-Of-Smalltalk.pdf

**Comment by NewAlexandria** [comment]
[Here is a gist](https://gist.github.com/NewAlexandria/d0ea7060d9ab8b7c7cd2) that could be embedded in `github.io` page.  It hits the non-authenticated per-hour rate limit before finishing, though, so it's just a work in progress.

Does anyone know a way to piggyback on the user's token or related credential – or would an oauth login be needed?

**Comment by DarrenN** [comment]
Hey all - thanks for this, this is a great idea. We can definitely put something like this together using our existing systems for http://paperswelove.org and generate a nightly list. You're mostly interested in a recently added list?

**Comment by NewAlexandria** [comment]
Yes, that's correct.  Sounds well to add it to the website or `gh-pages` branch, since a Github API key can be generated for the access.

**Comment by Khalian** [comment]
So I had a look at this problem. Initially it made sense to write a shell script and upload it as a gist somewhere and put some markdown code in README.md which ran @gfixler code suggestion. Turns out its impossible to do it right now : https://github.com/github/markup/issues/199 as its a closed issue in github. So referencing this directly in the README.md or any markdown page is out of question. 

So my question is this. Can this be embedded as an AJAX / PHP code somewhere in the website?

**Comment by NewAlexandria** [comment]
A `gh-pages` site can load a JS file, and that can do what is needed.  I think the code would need to lean on a Github API key to do the request, as GH avoids giving access to scripts in order to avoid unthrottled scraping.

**Comment by DarrenN** [comment]
We do a fair amount of dynamic generation and API scraping offline for the site now (before pushing the static files up to GitHub). We could add this to the current process which gathers meetup.com data for the upcoming posts. That would update the list every 6 hours when the job runs.

**Comment by evaryont** [comment]
If there is an automated process, integrating it. Generating a list of all of the papers added in the past 7 or so days, regardless of the number (so there is a chance of blowing up the page in a big commit). By making it time-centric rather than a hard count, it would make it easy to generate an RSS feed of those recent papers.

**Comment by DarrenN** [comment]
If someone wants to put together a Ruby/Python/Clojure script to generate a YAML or JSON file with the most recent papers we can add it to the build process to generate a page. Happy to talk through specs with any volunteers.

**Comment by NewAlexandria** [comment]
@DarrenN can you show a demo of the output format?

**Comment by Khalian** [comment]
I can take it up. What are the technical specs needed exactly?

**Comment by DarrenN** [comment]
* Script needs to be self contained so we can run it as part of our existing cron jobs. 
* API Keys and output dir should be set with `ENV` vars, such as `GITHUB_API_KEY` and `OUTPUT_DIR`

### Output formats

Either YAML or JSON are fine (the output will get consumed by our Ruby site generator).

**YAML**:

```yaml
- papers: 
  - {
      url: "https://github.com/papers-we-love/papers-we-love/blob/master/caching/2q-a-low-overhead-high-performance-buffer-management-replacement-algorithm.pdf", 
      commit: "the commit message", 
      commit_date: "2015-10-01T00:00:00.000Z"
     }
```

**JSON**

```json
[
  {
    "papers": [
      {
        "url": "https://github.com/papers-we-love/papers-we-love/blob/master/caching/2q-a-low-overhead-high-performance-buffer-management-replacement-algorithm.pdf", 
        "commit": "the commit message", 
        "commit_date": "2015-10-01T00:00:00.000Z"
      }
    ]
  }
]
```

**Tricky bits**:

1. We don't get the real titles of the PDFs, just the urls. I do have a set of scripts that pop open the PDFs and do some searching to make an educated guess, so may be able to use those to walk the output of this script and get human readable titles. That script is in Racket if anyone wants to try an incorporate it.
1. Using the GitHub API will cover actual PDF files that are committed to the repo, but it won't cover entries that are only added to the READMEs in each folder, unless someone wants to try and parse commit diffs to extract new entries.
1. We should probably limit the output to 10 entries.

**Comment by DarrenN** [comment]
Along these lines, one idea we've discussed internally is adding a JSON file to each folder within the repo to accompany the README file which contains metadata about the papers themselves, a sort of expanded version of [BibTex](http://www.bibtex.org/Format/). One of the reasons I've been working on PDF processing is to rip through the repo and start to generate said files.

**Comment by zeeshanlakhani** [comment]
So happy to see traction on this @DarrenN @NewAlexandria @Khalian!

**Comment by NewAlexandria** [comment]
@DarrenN do you know about [pdfinfo and cb2bib](http://stackoverflow.com/a/1851113/263858)?

**Comment by DarrenN** [comment]
@NewAlexandria I do know about pdfinfo but it was surprisingly unhelpful with many of our PDFs as most don't have proper metadata dicts. What I found to work a lot better is to convert the PDFs to XML with [Poppler](https://poppler.freedesktop.org/) and then do some heuristics to get what looks like the title. I then hit [DBLP](http://dblp.uni-trier.de)'s search API to try and get the right metadata. When I get multiple search results I do a quick L-distance check to find the one closest to what I want.

Will take a look at cb2Bib, was unfamiliar with it.

**Comment by DarrenN** [comment]
The Racket script I have for this gives pretty good results, its just slow due to making web requests:

```scheme
(fetch-paper "An Axiomatic Basis for Computer Programming")
'(#hasheq((url . "URL#3232025")
          (info
           .
           #hasheq((authors . #hasheq((author . "C. A. R. Hoare")))
                   (url . "http://dblp.org/rec/journals/cacm/Hoare69")
                   (number . "10")
                   (title . "An Axiomatic Basis for Computer Programming.")
                   (venue . "Commun. ACM")
                   (volume . "12")
                   (pages . "576-580")
                   (year . "1969")
                   (type . "Journal Articles")))
          (@score . "6")
          (@id . "3232025")))
```

**Comment by joereynolds** [comment]
As a simple view, could we not just do @gfixler 's idea and use

```$ git log --name-status | \grep "^A\s" | grep -v README\.md | head```
And have that as a post commit hook that writes to a markdown file?

I imagine that would be very fast, and would require about 20-30 minutes of dev time

**Comment by DarrenN** [comment]
@joereynolds sounds great, care to spend the 20-30m of dev time?

**Comment by joereynolds** [comment]
@DarrenN consider it done, hopefully today or tomorrow

**Comment by joereynolds** [comment]
Here's the PR

https://github.com/papers-we-love/papers-we-love/pull/405
