### ISSUE TITLE
rescrape LA for this month

### ISSUE THREAD

**Issue by samlecuyer** [papers-we-love/papers-we-love#311]
We had a placeholder title because the actual paper was TBD.  Should read "Phil Freeman on Principal type-schemes for functional programs"

**Comment by DarrenN** [comment]
Hi @samlecuyer the script runs 4 times a day, so it should get picked up pretty soon.

**Comment by samlecuyer** [comment]
thanks @DarrenN I had no idea how often it ran. I'll stop opening these :)
