### ISSUE TITLE
directory for papers on hashing?

### ISSUE THREAD

**Issue by kmulvey** [papers-we-love/papers-we-love#318]
I wanted to add a paper on hashing (linked below) but wasn't sure what directory to put it in.

http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.25.4189&rep=rep1&type=pdf

**Comment by aaronwinter** [comment]
@kmulvey the `data_structures/` directory is the one you are looking for

**Comment by NewAlexandria** [comment]
Interesting paper
