### ISSUE TITLE
Papers We Love #20 - Tomas Petricek on Paul Feyerabend's The Against Method

### ISSUE THREAD

**Issue by zeeshanlakhani** [papers-we-love/papers-we-love#332]
@tpetricek
- [meetup](http://www.meetup.com/papers-we-love/events/225369741/)

*Sponsored By*

[![twosigma_rgb](https://cloud.githubusercontent.com/assets/202820/6004990/c9be60f2-aabb-11e4-97ca-e4543aabc6e6.jpg)](https://www.twosigma.com/)

[![600_433118808](https://cloud.githubusercontent.com/assets/202820/6473811/d24f23d0-c1c9-11e4-8330-a33897e25818.jpeg)](https://www.tumblr.com/_)

This issue has been created to start/spark/organize a conversation on the book **Against Method: Outline of an Anarchist Theory of Knowledge** by Paul Feyerabend!

Please offer up questions, comments, or additional information regarding this book/presentation.

## Description

How is computer science research done? What we take for granted and what we question? And how do theories in computer science tell us something about the real world? Those are some of the questions that may inspire computer scientist like me (and you!) to look into philosophy of science. I’ll present the work of one of the more extreme (and interesting!) philosophers of science, Paul Feyerabend. In “Against Method”, Feyerabend looks at the history of science and finds that there is no fixed scientific methodology and the only methodology that can encompass the rich history is ‘anything goes’. We see (not only computer) science as a perfect methodology for building correct knowledge, but is this really the case? To quote Feyerabend: 

> Science is much more 'sloppy' and 'irrational' than its methodological image.

I’ll be mostly talking about Paul Feyerabend’s “Against Method”, but as a computer scientist myself, I’ll insert a number of examples based on my experience with theoretical programming language research. I hope to convince you that looking at philosophy of science is very much worthwhile if we want to better understand what we do and how we do it as computer scientists! 

## Bio

Tomas Petricek ([@tomaspetricek](https://twitter.com/tomaspetricek)) recently submitted his PhD thesis at University of Cambridge on context-aware programming languages. He is active in the functional programming community, contributes to various F# open-source libraries, writes and talks about F# and offers trainings and consulting at fsharpWorks. When he isn’t writing equations or code, he enjoys reading philosophy of science books and occasionally publishes an essay combining philosophy and computer science.

**Comment by tcfuji** [comment]
This looks cool but isn't Against Method a book?

**Comment by zeeshanlakhani** [comment]
@tcfuji it is haha. We wanted to branch out and do something special for this event. Tomas actually referenced this book in his own research papers -> http://tomasp.net/academic/papers/philosophy-pl/philosophy-pl.pdf, so there's overlap.

**Comment by tcfuji** [comment]
Ah! As a philosopher in a past life I hope it will be recorded!

**Comment by zeeshanlakhani** [comment]
@tcfuji def. will be!

**Comment by tcfuji** [comment]
:+1:

**Comment by tpetricek** [comment]
Just in case someone was interested in the quotes, I finally uploaded the slides: http://tpetricek.github.io/Talks/2015/pwl-against-method/

**Comment by zeeshanlakhani** [comment]
Thanks @tpetricek!
