### ISSUE TITLE
Colorado link broken in README 

### ISSUE THREAD

**Issue by 2016rshah** [papers-we-love/papers-we-love#346]
The link for the Colorado Chapter of Papers We Love is broken. It is currently [http://papersweloveco.org](http://papersweloveco.org), but the connection will just time out. 

Perhaps we should change the link to their [twitter link](https://twitter.com/papersweloveco) or their [meetup group](http://www.meetup.com/Papers-We-Love-Boulder/). I would be happy to submit a pull request if you would like :smiley:

**Comment by zeeshanlakhani** [comment]
@2016rshah please put in a PR! Thanks!

**Comment by 2016rshah** [comment]
Any preference on the twitter link or the meet up link?

**Comment by zeeshanlakhani** [comment]
Meetup-link @2016rshah :).
