### ISSUE TITLE
Use the GitHub organization to host chapter repositories

### ISSUE THREAD

**Issue by RichardLitt** [papers-we-love/papers-we-love#348]
### What

I'm suggesting we adopt a NodeSchool like chapter system, where each chapter gets their own repository in order to help organizers coordinate efforts and cut down on time and resources spent figuring out management.

#### Help Organizers coordinate
I'm currently looking into how to host a Papers We Love in Boston. It's not difficult to do - find a speaker, find a space, let people know it exists, set up a MeetUp group. However, as I'm working with a coorganizer, we have to figure out a way to talk to each other outside of Twitter direct messages. I'd like to be able to use a GitHub repository to use issues for discussion of how to do this, largely because that would allow a way for community members to vote on papers closer to the source, because it's what I'm used to doing with NodeSchool and other organizations, and because it doesn't use Meetups rather poor tools for discussion. 

#### Cross-pollinate ideas about how to coordinate
It would be good to have a standard way of communicating with coorganizers so that chapters can learn from each other how to better organize, too. 

#### People are already doing this
Some chapters already have their own GitHub repositories, or organizations: [papers-we-love-rtp](https://github.com/papers-we-love-rtp), [Munich](https://github.com/papers-we-love-munich), [Bangalore](https://github.com/papers-we-love-blr/love), [Hyderabad](https://github.com/punchagan/papers-we-love-hyd). Some individuals set up issues for their talks, too, like these in [Chicago](https://github.com/seancribbs/pwl-chicago-1), and [London](https://github.com/philandstuff/pwl-london-equal-rights). I think keeping this in the PapersWeLove organization would be more useful. 

#### Chapter histories could be maintained
Finally, Boston's PapersWeLove chapter used to exist, and now it doesn't. Without some sort of history - which would have happened if there were closed issues on the GitHub repo, instead of just a deleted Meetup group - I don't know why it failed to continue, what caused the chapter to fall apart, and how those issues might be alleviated (or indeed, not. Maybe Boston isn't a good place for Papers We Love.).

### How

Set up a repo to help organizers, like this [nodeschool one](https://github.com/nodeschool/organizers). Create a team called `chapter-organizers`, and give members access to edit their new chapter repo, e.g. https://github.com/paperswelove/boston.

**Comment by zeeshanlakhani** [comment]
@RichardLitt hey! Thanks for this. We're taking a closer look at NodeSchool, and we'll write some more thoughts soon. Hopefully, other organizers will chime in on this. If they think it will help, we'll definitely create a team and get things up-and-running.

In terms of the Boston chapter, maybe @ashleygwilliams can give you more insight into the history.

**Comment by zeeshanlakhani** [comment]
Also, @RichardLitt, the thought is that there would still be the central repo for all the papers/general-info... and *local* repos for the chapters, which focus on archiving chapter histories' and integral information/communication about each chapter event (e.g. venue, turnout, questions)?

We do now have a PWL Slack, with specific chapter channels, which may work better or *in-addition to*. Signup is at http://papersweloveslack.herokuapp.com/ (slack is https://paperswelove.slack.com). It may be better to discuss this there.

**Comment by RichardLitt** [comment]
@zeeshanlakhani Thanks! NodeSchool is a great resource for seeing how a large-scale, acephalous GitHub organization can work with autonomous nodes. The [readme.md](https://github.com/nodeschool/organizers) for nodeschool/organizers has a lot of information on how they do it now, as well as the issues. 

Asking @ashleygwilliams about what happened to Boston makes sense, but I think that in general we should be able to find out about a chapter's history without asking someone, as that creates a point of failure in knowledge transmission (I'm 100% aware of how awkward a phrasing that is). Hypothetically, what if the original person isn't around anymore, or doesn't want to talk about PWL, or was the center of a code of conduct controversy? Having a place to record issues fixes that, I think. 

Slack sounds good, but the fees for history are exorbitant. It'll certainly help with synchronous communication, though. I think we should discuss this here - there are more stakeholders in the watchers of this repository than will be in the Slack room.

**Comment by zeeshanlakhani** [comment]
Thanks for the reply @RichardLitt. Let's definitely discuss on the Slack. We'd still need organizers' buy-in of course to make it happen. 

Also, still wondering if you'd clarify:

```
Also, @RichardLitt, the thought is that there would still be the central repo for all the papers/general-info... and local repos for the chapters, which focus on archiving chapter histories' and integral information/communication about each chapter event (e.g. venue, turnout, questions)?
```

but we can hash such questions out in the chat as well.

**Comment by RichardLitt** [comment]
Ah, sorry.

> Also, @RichardLitt, the thought is that there would still be the central repo for all the papers/general-info... and local repos for the chapters, which focus on archiving chapter histories' and integral information/communication about each chapter event (e.g. venue, turnout, questions)?

Exactly. The local repositories could also be used to copy over papers which have been presented at those venues, so that users know what sort of papers their local chapter is a fan of, what has been presented before, etc.

**Comment by RichardLitt** [comment]
How do we move forward with this?

**Comment by DarrenN** [comment]
@zeeshanlakhani / @jeremyheiler lets plan logistics this weekend

**Comment by RichardLitt** [comment]
Ping me on Slack if you do it over there. I'm around and happy to help.

**Comment by DarrenN** [comment]
@RichardLitt this is in motion https://github.com/papers-we-love/organizers

**Comment by DarrenN** [comment]
Complete
