### ISSUE TITLE
Broken link missing an `l`

### ISSUE THREAD

**Issue by 2016rshah** [papers-we-love/papers-we-love#349]
In the README, in [this subsection](https://github.com/papers-we-love/papers-we-love#other-good-places-to-find-papers), the link for `Research Papers from Robert Harper, Carnegie Mellon University` is broken. It is just missing the `l` at the end of `html` in the link so it returns a 404.

Rather than [http://www.cs.cmu.edu/~rwh/papers.htm](http://www.cs.cmu.edu/~rwh/papers.htm) the link should be [http://www.cs.cmu.edu/~rwh/papers.html](http://www.cs.cmu.edu/~rwh/papers.html)

**Comment by zeeshanlakhani** [comment]
ah, super thanks @2016rshah. Mind just putting the PR in? always go for it!
