### ISSUE TITLE
Consider using LFS extension for large files

### ISSUE THREAD

**Issue by NewAlexandria** [papers-we-love/papers-we-love#351]
As per [this recent GitHub post](https://github.com/blog/2069-git-large-file-storage-v1-0) there is a new option for managing large files in a repo.
- Someone should probably test this first in a fork.  
- A list of commands / instructions for use will be needed
- Also, the contributing info will need to be updated.
- If contributing and use is too difficult, then this may not be for us.

I can do this eventually; I just wanted to write out some ideas for how to rapidly create adoption, if this looks like a worthwhile thing.

**Comment by zeeshanlakhani** [comment]
Will attempt to take a look at this again.
