### ISSUE TITLE
Add PWL Kathmandu to list of active chapters

### ISSUE THREAD

**Issue by kaflesudip** [papers-we-love/papers-we-love#359]
We held our [first meetup](https://www.facebook.com/events/744766289001751/) today and have decided to organize meetup each month. Few images from the meetup can be found [here](https://twitter.com/search?q=%23pwlkathmandu&src=typd). We would like to list PWL Kathmandu as an active chapter.

**Comment by DarrenN** [comment]
@kaflesudip - fork papers-we-love.github.io and add your chapter to the [chapters.yml](https://github.com/papers-we-love/papers-we-love.github.io/blob/middleman/source/chapters.yml) file. Then create a PR.

**Comment by kaflesudip** [comment]
We don't have a meetup page and instead operate with facebook group. Can we leave meetup url?

**Comment by DarrenN** [comment]
Leave the `meetup_url` key blank. We won't be able to display your meetups on the Kathmandu chapter page.

**Comment by zeeshanlakhani** [comment]
@kaflesudip also, please add a PR for the chapter to the README of the repo, e.g. https://github.com/papers-we-love/papers-we-love/pull/287.

**Comment by zeeshanlakhani** [comment]
@kaflesudip just pinging you again!

**Comment by kaflesudip** [comment]
Sorry I missed on this one. I will add it ASAP.

**Comment by kaflesudip** [comment]
I have sent the PR.

**Comment by DarrenN** [comment]
Done https://github.com/papers-we-love/papers-we-love/pull/369
