### ISSUE TITLE
The Washington, DC chapter meetup page is gone

### ISSUE THREAD

**Issue by adamcrosby** [papers-we-love/papers-we-love#382]
[Their twitter](https://twitter.com/paperswelovedc) is apparently looking for a new organizer, but the Meetup link in Readme.md is dead.  I wasn't sure if removing it or noting they need a new organizer would be better?

**Comment by DarrenN** [comment]
Agreed, we should pull the link.

**Comment by zeeshanlakhani** [comment]
Yep.. and will add Korea to the list.

**Comment by zeeshanlakhani** [comment]
nice, i did the latter ;).
