### ISSUE TITLE
Create a  'Language' directory for all language related papers

### ISSUE THREAD

**Issue by joereynolds** [papers-we-love/papers-we-love#402]
There are quite a few languages in the top level directory (Clojure, haskell, Smalltalk etc...). In my eyes, the top-level should be very generic and then drill down into a greater level of detail as you explore the directories.

Thoughts?

**Comment by zeeshanlakhani** [comment]
@joereynolds i'm in agreement—better sub-categorization really. Do you think you could start the work/try-out a better directory structure for us to review and aid with?

**Comment by joereynolds** [comment]
Yep no problem, will try and sort something out tomorrow
