### ISSUE TITLE
New Chapter - Novo Capítulo

### ISSUE THREAD

**Issue by Alessandrobarros265** [papers-we-love/papers-we-love#418]
Hi, I'm Alessandro and would like you to participate in the Papers We Love please, I would like to have in my city, Teresina - PI, Brazil. I am coorganizador Meetup.

https://www.meetup.com/pt-BR/Papers-We-Love-Teresina/

Name: Alessandro Barros Leal
Email: ale_alessandro_ale@hotmail.com

Oi, sou o Alessandro e gostaria que vocês de participar do Papers We Love por favor, gostaria de ter um na minha cidade, Teresina -  PI, Brasil. Sou coorganizador do Meetup.

https://www.meetup.com/pt-BR/Papers-We-Love-Teresina/

Nome: Alessandro Barros Leal
Email: ale_alessandro_ale@hotmail.com

**Comment by hakutsuru** [comment]
Team:

I created the teresina repo, invited chapter organizer to collaborate via github, and sent an update via email. 

If no one has comments, I will close this issue later this week.

**Comment by hakutsuru** [comment]
@Alessandrobarros265 Teresina is setup - https://github.com/papers-we-love/teresina

Once you accept the invitation for the organizers team please update the Readme and Code of Conduct with your chapter's information.
