### ISSUE TITLE
Create an automated way of refuting PDF submissions for papers with strict licensing 

### ISSUE THREAD

**Issue by newsomc** [papers-we-love/papers-we-love#44]
Soliciting ideas.

We need a list of publishers that do not allow redistribution of papers. We can then parse PDFs with this list and a simple python script, and reject files that appear to be under copyright. 

- create a list of publishers
- write a python script to parse pdfs with list
- add to post commit hook to reject files that appear to be under copyright

**Comment by DarrenN** [comment]
Closed due to inactivity
