### ISSUE TITLE
Zürich chapter is up and running!

### ISSUE THREAD

**Issue by utaal** [papers-we-love/papers-we-love#443]
Founded by Kornilios Kourtis (@kkourt) with me and Vasia Kalavri (@vasia).

We held the first meet up last month, https://www.meetup.com/Papers-we-love-Zurich/events/237963794/ (Naiad: A Timely Dataflow System, presented by me). The next is on Thursday, https://www.meetup.com/Papers-we-love-Zurich/events/238755473/ and we have two more papers (and speakers) in the pipeline for May and June (or possibly June and July).

**Comment by utaal** [comment]
@DarrenN we've followed the guide [here](https://github.com/papers-we-love/organizers), are any other steps necessary? Am I missing something?
Thanks!

**Comment by DarrenN** [comment]
Hello @utaal - check out https://github.com/papers-we-love/organizers

**Comment by DarrenN** [comment]
@utaal add your chapter to the README in a PR https://github.com/papers-we-love/papers-we-love/blob/master/README.md

Thanks!
