### ISSUE TITLE
Lebanon chapter had its first meetup

### ISSUE THREAD

**Issue by saeidw** [papers-we-love/papers-we-love#444]
I'm happy to announce that we held our first meetup on April 17th. The event page is on our Facebook group ([https://www.facebook.com/events/176439382874892/](https://www.facebook.com/events/176439382874892/)). We introduced Papers We Love, discussed the paper "How to Share a Secret" by Adi Shamir, and agreed on a format and ideas for future meetups.

I've posted a link to the paper to our [chapter repository](https://github.com/papers-we-love/lebanon) and updated our contact information.

We plan to hold our next event on May 8th.

**Comment by DarrenN** [comment]
@saeidw congrats!

Please do the following:

- Add a chapter entry to https://github.com/papers-we-love/papers-we-love.github.io/blob/middleman/source/chapters.yml
- Add a matching chapter template to https://github.com/papers-we-love/papers-we-love.github.io/tree/middleman/source/partials/chapters
- Add your chapter to the README https://github.com/papers-we-love/papers-we-love/blob/master/README.md

**Comment by saeidw** [comment]
Thank you, @DarrenN. I submitted pull requests with the necessary changes. Please let me know if there's anything I should add.

**Comment by jeremyheiler** [comment]
👍
