### ISSUE TITLE
findpaperswelove.com has expired

### ISSUE THREAD

**Issue by diego898** [papers-we-love/papers-we-love#453]
When I click on "Papers" on the home page, it goes to: 

http://findpaperswelove.com/#!/ 

which shows the domain has expired:

![image](https://cloud.githubusercontent.com/assets/742407/26038601/c609b7e6-38c0-11e7-8104-3ff7b3b1f53d.png)

**Comment by DarrenN** [comment]
Wrong repo - this is an issue with https://github.com/papers-we-love/papers-we-love.github.io
