### ISSUE TITLE
Security/Internet Census via Insecure Routers (2012) link dead

### ISSUE THREAD

**Issue by RNabel** [papers-we-love/papers-we-love#454]
The original link is: http://internetcensus2012.bitbucket.org/paper.html
but redirects to: http://bitbucket.org

Working Internet Archive link: https://web.archive.org/web/20130321001839/http://internetcensus2012.bitbucket.org/paper.html

Are Internet Archive links acceptable?

**Comment by deltamualpha** [comment]
Looks like it's also at http://internetcensus2012.github.io/InternetCensus2012/paper.html, which might be better.

**Comment by RNabel** [comment]
Cool, both links work... strange. Thank you for checking :)
