### ISSUE TITLE
Chapter Teresina is running and needs publicity in the Official PWL Web Site

### ISSUE THREAD

**Issue by thiagocsousa** [papers-we-love/papers-we-love#461]
We held our two first meet up last month, https://www.meetup.com/pt-BR/Papers-We-Love-Teresina/. The next is on next Tuesday, but we did not appear in the June Meetups. Even in the first web site page does not appear the chapter of Teresina. Are we missing something? Thanks in advance.

**Comment by DarrenN** [comment]
@thiagocsousa you have to add yourself to https://github.com/papers-we-love/papers-we-love.github.io/blob/middleman/data/chapters.json

Please make a PR.
