### ISSUE TITLE
Markdown versions of papers.

### ISSUE THREAD

**Issue by thaggie** [papers-we-love/papers-we-love#467]
I don't know whether this would be legally allowed due to copyright etc. but would it be possible to make markdown copies of papers (I'm imagining humans doing this not machines) so that they're more easily readable - I find I have to print pdfs out to read them.

**Comment by DarrenN** [comment]
It might be possible to do this with tooling like Poppler and Pandoc, but not something we would pursue at this time. It is an interesting idea for sure. If you are interested in getting a group together to come up with a programmatic solution we could run across the repo we might be interested.
