### ISSUE TITLE
Add Budapest chapter link to main site

### ISSUE THREAD

**Issue by danimad** [papers-we-love/papers-we-love#468]
Hi,
We had our [second talk](https://github.com/papers-we-love/budapest), and the third is already planned for September. Could you add the Budapest chapter to the main sites?
Thanks!

**Comment by DarrenN** [comment]
Hi @danimad - please open two PRs:

- Add your chapter to the README in https://github.com/papers-we-love/papers-we-love/blob/master/README.md
- Add your chapter to https://github.com/papers-we-love/papers-we-love.github.io/blob/middleman/data/chapters.json and create a page for your chapter in https://github.com/papers-we-love/papers-we-love.github.io/tree/middleman/source/partials/chapters (you can copy an existing template, such as Zurich or New York and update the information)

**Comment by danimad** [comment]
Hi @DarrenN,

Sorry for the wait. I created the two pull requests:
https://github.com/papers-we-love/papers-we-love/pull/472
https://github.com/papers-we-love/papers-we-love.github.io/pull/115

I'm not really experienced with this, I hope everything is okay.
If not, let me know!
