### ISSUE TITLE
Add hashgraph distributed consensus

### ISSUE THREAD

**Issue by MartyGentillon** [papers-we-love/papers-we-love#471]
The hashgraph distributed concerns algorithm is very interesting.  It functions like a block chain with latencies that are closer to Paxos.

https://en.m.wikipedia.org/wiki/Hashgraph
http://www.swirlds.com/wp-content/uploads/2016/07/SWIRLDS-TR-2016-01.pdf

**Comment by DarrenN** [comment]
Hi @MartyGentillon could you make a PR to add this to the repo?

**Comment by DarrenN** [comment]
Example: https://github.com/papers-we-love/papers-we-love/pull/469

**Comment by MartyGentillon** [comment]
Finally got to it, done.
