### ISSUE TITLE
Iowa City chapter official!

### ISSUE THREAD

**Issue by geemus** [papers-we-love/papers-we-love#481]
Hey, as per the organizer doc, just wanted to report back that we had our first meetup last night and it went really well. Would love to join the official list of chapters. Thanks!

**Comment by Randommood** [comment]
💯  so great to hear @geemus !!

**Comment by geemus** [comment]
@Randommood ! it's been ages, hope we bump into each other again soon.

**Comment by DarrenN** [comment]
Hi @geemus - congrats on the meetup! Please open a PR adding yourself to the chapter list in the README - https://github.com/papers-we-love/papers-we-love/blob/master/README.md

Thanks!
