### ISSUE TITLE
Paper We Love Porto Alegre, Brazil

### ISSUE THREAD

**Issue by rafaelpsouza** [papers-we-love/papers-we-love#497]
Hi guys,

I'm Rafael Souza [@rafael_psouza](https://twitter.com/rafael_psouza) I live in Porto Alegre, Brazil and I'm a software engineer and [Ubots](http://ubots.com.br/) Co-founder. I think Papers We Love is a greate opportunity for the local community and I'm thinking of starting a local chapter (already invited some friends to helpe me).

I already gave talks and supported local software development events (like [Qcon Rio](http://qconrio.com/rio2015/presentation/api-management-um-aliado-para-construcao-de-apis.html), and [The Developers Conference](http://www.thedevelopersconference.com.br/tdc/2017/portoalegre/trilha-chatbots-e-interfaces-conversacionais)) and I'll be glad to host PWL Porto Alegre!

**Comment by DarrenN** [comment]
@hakutsuru

**Comment by DarrenN** [comment]
Hi @rafaelpsouza - thanks for your interest in starting a PWL chapter in Porto Alegre. We have some instructions in this repo on getting started with a new chapter https://github.com/papers-we-love/organizers
