### ISSUE TITLE
Investigate citation-style-language/schema to create citations

### ISSUE THREAD

**Issue by newsomc** [papers-we-love/papers-we-love#52]
https://github.com/citation-style-language/schema

**Comment by DarrenN** [comment]
@newsomc is the idea to generate JSON files for each folder with citation data?

**Comment by newsomc** [comment]
Yeah, exactly. Is really just a nice to have though.

**Comment by NewAlexandria** [comment]
Does this enable an integration with any particular app or other thing?

**Comment by newsomc** [comment]
@NewAlexandra, nothing has been developed as of yet.

**Comment by newsomc** [comment]
@NewAlexandria, nothing has been developed as of yet.

**Comment by DarrenN** [comment]
So, I'm keeping this open as an exploratory topic. I'm wondering if we couldn't automate this a bit (walk the papers in the repo) and generate some of the JSON from PDF metadata. 

Having a JSON file in a consistent format in each folder would allow me to expand what the PWL site can do, perhaps generating an index during compile.

The downside will be papers that are just linked (not in the repo). In theory I could pull those down and extract metadata as well, but it adds some complexity.

**Comment by DarrenN** [comment]
The citation schema might not be the best format, as its primarily for citation bibliographies within papers, but it will probably server as a good jumping off point and there might be another schema used for papers themselves.

**Comment by NewAlexandria** [comment]
I think I've heard of some library tools for doing this.  Maybe let's reach out to our network for anyone in who works in a library, and may know of a good tool.

**Comment by mrallen1** [comment]
@DarrenN Academic search engines (like this one from MSFT) have APIs. http://academic.research.microsoft.com/About/Help.htm#4 - maybe you could use that to build this tool. I bet they have electronic citation information already there.

**Comment by DarrenN** [comment]
@mrallen1 - thanks for that! MS Academic Search seems to do very much what I want, providing Bibtex data for papers. Will be applying for an API key shortly.

**Comment by mrallen1** [comment]
:cake:
