### ISSUE TITLE
Unikernel Papers

### ISSUE THREAD

**Issue by holmeshe** [papers-we-love/papers-we-love#520]
I would like to add some good papers about Unikernel, they are

## Unikernels (LibOS)

* [Unikernels: Library Operating Systems for the Cloud](https://dl.acm.org/citation.cfm?id=2451167)
* [IncludeOS: A minimal, resource efficient unikernel for cloud services](https://ieeexplore.ieee.org/document/7396164/)
* [The rump kernel: A tool for driver development and a toolkit for
applications](https://www.netbsd.org/gallery/presentations/justin/2015_AsiaBSDCon/justincormack-abc2015.pdf)

### High Availability Through Unikernel
* [Tardigrade: Leveraging Lightweight Virtual Machines to Easily and Efficiently Construct Fault-Tolerant Services](https://www.usenix.org/node/189029)

**Comment by DarrenN** [comment]
@holmeshe Great! Please create a pull request.

Thanks
