### ISSUE TITLE
Papers we love - Coimbatore

### ISSUE THREAD

**Issue by 62ramya** [papers-we-love/papers-we-love#529]
Hi Team,

I'm Ramya Vellingiri from KGISL (www.kgisl.com)  Coimbatore, Tamilnadu. We would like to start a local chapter in Coimbatore which will benefits Professionals, Faculties, and students in Coimbatore.  KGISL is helping out to run the show. 

Hoping for the response. 

Thanks,
Ramya V

**Comment by hakutsuru** [comment]
Ramya Vellingiri: Would you be the only organizer to start, or will you be working with others to organize the chapter?

We are a bit busy with PWLConf, but I will try to set this up in the next several days.

**Comment by 62ramya** [comment]
Hi,

We are planning to have a few others from each different profession to be
part of organizing teams.

Regards,
Ramya Vellingiri

**Comment by hakutsuru** [comment]
@62ramya -- Coimbatore is setup - https://github.com/papers-we-love/Coimbatore

Once you accept the invitation as collaborator, please update the Readme and Code of Conduct with your chapter's information.

With abuse and harassment recently in the (North American) news, we hope every new chapter will embrace our mission to foster open and accepting communities -- so please read the Code of Conduct, and let us know if it can be improved (or made more culturally aware).

You are encouraged to join our slack -- http://papersweloveslack.herokuapp.com/

If you create a Meetup page (or other social media), we can provide you with branded graphics.

Welcome aboard.

**Comment by 62ramya** [comment]
Hi,

Thanks for setting this up. Happy to be part of it.

Regards,
Ramya Vellingiri

**Comment by 62ramya** [comment]
And we will be creating a twitter handle and meetup page. It would be great
if we get branded graphics.

Thanks,
Ramya Vellingiri

**Comment by hakutsuru** [comment]
@DarrenN - About the graphics...

**Comment by DarrenN** [comment]
@62ramya please let us know once you've had your first meetup.

**Comment by 62ramya** [comment]
Sure.


Thanks,
Ramya Vellingiri
