### ISSUE TITLE
From Game Design Elements to Gamefulness: Defining “Gamification” link 404s

### ISSUE THREAD

**Issue by thejessleigh** [papers-we-love/papers-we-love#530]
It looks like this paper is no longer available at its original location. I was able to find the same paper [here](http://www.rolandhubscher.org/courses/hf765/readings/Deterding_2011.pdf), but it seems like the paper is copyrighted in the US by ACM and I didn't know if it would be a violation of the contribution guidelines to add this link. Let me know, and I'll either add this link, or link to where you can buy the paper on ACM's site. Thanks

**Comment by TomCoded** [comment]
License looks like it's okay for non-commercial usage but the link in PWL's copyright policy links to a site that doesn't load as an example of a problematic license, so I'm not sure what the group standards are. (https://www.acm.org/publications/policies/copyright-policy-v1)  I suppose the group can also ask the ACM to clarify if it's unclear based on whatever standards the group uses.

**Comment by deltamualpha** [comment]
@TomCoded #531 will fix the buggy link, but the general point of the ACM's copyright assertion available at https://www.acm.org/publications/policies/copyright-policy.
