### ISSUE TITLE
Papers We Love - Mumbai

### ISSUE THREAD

**Issue by 83bytes** [papers-we-love/papers-we-love#533]
Hello,

I am trying to set up Papers We Love Mumbai in Mumbai, India.
We plan to host our first meetup very soon. 

Please create the chapter repo. 

Thank You,
Sohom.

**Comment by hakutsuru** [comment]
@83bytes -- Mumbai is setup - https://github.com/papers-we-love/mumbai

Once you accept the invitation as collaborators, please update the Readme and Code of Conduct with your chapter's information. As an admin for the mumbai repo, you can add other collaborators.

With abuse and harassment recently in the (North American) news, we hope every chapter will embrace our mission to foster open and accepting communities -- so please read the Code of Conduct, and let us know if it can be improved (or made more culturally aware).

You are encouraged to join our slack -- http://papersweloveslack.herokuapp.com/

Welcome aboard.

**Comment by 83bytes** [comment]
Thank You.
:-)
