### ISSUE TITLE
Is there a way to say "I am looking for feedback on my paper"?

### ISSUE THREAD

**Issue by guettli** [papers-we-love/papers-we-love#534]
Since some months I am collecting small guidelines:

   https://github.com/guettli/programming-guidelines/

Now I am looking for feedback.

Maybe I was blind, but I could not find a hint how to find feedback via "papers we love".

Is creating an issue like I just did the right way?

**Comment by DarrenN** [comment]
Hi @guettli - yes opening an issue to ask questions is fine. We don't currently have a formal mechanism for asking for feedback. We're primarily a volunteer driven organization. Would be better to take your request to the community on [Slack](http://papersweloveslack.herokuapp.com/) or Twitter.
