### ISSUE TITLE
Are distributed file systems papers already included?

### ISSUE THREAD

**Issue by ramlaxman** [papers-we-love/papers-we-love#539]
As I haven't found out papers, on HDFS, GlusterFs and other Distributed FS. If they are already there, please comment on this issue.

Thanks for the time.

**Comment by DarrenN** [comment]
If they're not in https://github.com/papers-we-love/papers-we-love/tree/master/distributed_systems then probably safe to add.

**Comment by 056942293** [comment]
###

**Comment by NewAlexandria** [comment]
Looking at that readme, it could use some cleanup.  @ramlaxman if you make a PR with new papers, I can help / offer a cleanup PR after that, with some ordering

**Comment by hakutsuru** [comment]
> could use some cleanup

@ramlaxman & @NewAlexandria Hope you are well. Those papers sound like welcom additions.

Think I suggested this elsewhere, but if anyone runs into a situation where a paper legitimately seems to fit with multiple categories... Consider adding a links to readme docs which are related.

Listing one paper in multiple places is not a big deal, if it is a link.

For hosted papers, there should only be one copy, so those must be in an optimal location and/or use linking for multiple reference.

**Comment by hakutsuru** [comment]
@NewAlexandria Checking open PRs, there is one on this already, which was close...
https://github.com/papers-we-love/papers-we-love/pull/540

Maybe this weekend, I can resolve the two current content PRs. Would you have tips on that? If there is no standard way, I can just merge, then clean up. But I dislike including PDFs which should not be here, even momentarily.

**Comment by ramlaxman** [comment]
Thanks @hakutsuru. I got it. From next time, I will try to use explicit reference instead of PDF. As far as I again reviewed this, I think we can close it. Please let me know if any help if needed from my side.
