### ISSUE TITLE
Found a dead link

### ISSUE THREAD

**Issue by youyinnn** [papers-we-love/papers-we-love#541]
[distributed_systems](https://github.com/papers-we-love/papers-we-love/blame/7c801a1090fc8ae75a8fc35ebc2881001f9fa436/distributed_systems/README.md#L12)

You can refer it from [here](http://citeseerx.ist.psu.edu/viewdoc/download;jsessionid=5A960A7B16A7BB42A99D7B6EFC30FB25?doi=10.1.1.41.7628&rep=rep1&type=pdf) now

**Comment by DarrenN** [comment]
@youyinnn care to open a PR with the update?

**Comment by youyinnn** [comment]
@DarrenN committed one plz check [here](https://github.com/papers-we-love/papers-we-love/pull/542#issue-271988953)
