### ISSUE TITLE
Requesting to add a list of BCIpaper. 

### ISSUE THREAD

**Issue by mhmohona** [papers-we-love/papers-we-love#576]
It would be really great if a list for Brain-Computer Interface papers is added.

**Comment by hakutsuru** [comment]
Would you feel comfortable creating a pull request to add this list?

**Comment by mhmohona** [comment]
Yea, definitely @hakutsuru! Will do it.

**Comment by mhmohona** [comment]
Hello @hakutsuru, I have added a list as you suggested. I will be really glad if you review it and let me know what you are thinking about it.

**Comment by hakutsuru** [comment]
Thank you! I reviewed the pull request, and after minor changes, I believe it will be merged. Once we get this merged, please close this issue (or we will do it during a cleanup sweep, but that could be a while).
