### ISSUE TITLE
Questions about where to add papers

### ISSUE THREAD

**Issue by pdgonzalez872** [papers-we-love/papers-we-love#580]
Hi! I'm new to this project and I love it!

I want to add a couple of links to this project and would like to know where to do so. Seems like you organize papers based on their category (eg: `distributed_systems`).

Let's take Erlang for example which is popular for distributed systems and concurrency. I expect papers that involve it to be in those categories. After doing a [search](https://github.com/papers-we-love/papers-we-love/search?q=erlang&unscoped_q=erlang) you can see that the same paper appears in a couple of places: `concurrency, distributed systems and languages`.

My goal is to help curate and maintain papers around [`Elixir`](https://elixir-lang.org/) (language).

So, a couple of questions:
1 - Do I create an `elixir` folder in [languages](https://github.com/papers-we-love/papers-we-love/tree/7c801a1090fc8ae75a8fc35ebc2881001f9fa436/languages) and add the papers there?
2 - Do I add the papers to their own specific category?
3 - Should I do both 1 and 2?
4 - Do I note anywhere that the papers use/discuss Elixir in any way? Maybe add to the link description?  Eg: `Making Reliable Distributed Systems in the Presence of Software Errors | Erlang`
5 - Is there a way to search (a `grep` of link titles would be sufficient for my use case) for the language the papers use/discuss other than searching through the papers themselves?

Please let me know your thoughts. Thanks for maintaining this project!

Paulo Daniel

**Comment by NewAlexandria** [comment]
I'd suggest that the answer will be paper-specific.  `languages` commonly has papers that are specific to the language itself, and less about what you when implementing it.  Otherwise, most papers would go into the language-specific folder for what someone used to validate their thesis.

We do have some papers that address a given topic, specifically related to a compiler's solution to said matter.  IMO, I would still put the paper until the topical folder, not the language folder.  But this is a strong opinion on it, and I know others may not agree.

Again, my summary is that only things that should go in the `language` tree are things that specifically relate to the meta-study of the language itself.  GLad for others' thoughts

**Comment by pdgonzalez872** [comment]
@NewAlexandria thanks for the reply. I see your point and I agree with it. Adding that `languages` folder seems to be asking for duplicates. Maybe there should be some docs saying exactly what you mentioned above about the papers being about the language itself and not using said language.

I guess the question (my use case) I want to be able to answer when looking at a paper collection is:

- What are the papers that have used Elixir in any capacity?

Whether they used Elixir for code examples, analyzed its features, etc. Anything mentioning Elixir I'd like to know about. Do we have a mechanism for that? Should we think about including such mechanism? For my use case, a title formatting mechanism would suffice, as I mentioned above.

**Comment by NewAlexandria** [comment]
Not that I can see.   

A repo is a simple way to organize such info.  Github-native seach does not index PDFs and binary files.  Setting up a convention or script that supported that is definitely the topic of it's own issue/suggestion.  Several times people have tried to propose things.  The right solution needs to be maintainable, ideally with near-zero maintenance, and not be a separate site. 

* a manually-added language tag (convention), per article entry
* a pre/post-commit hook that searches PDFs, matches for language, and adds per-article 'tags' automatically.

Either of these may not be ideal; they're just off-the-top-of-my-head

**Comment by pdgonzalez872** [comment]
Agree, the solution must be simple and hands-off.

I would 100% stay away from PDF parsing, I don't think that's a good approach.

My suggestion would be doing #4 in my first comment (and the first bullet point in your above comment) for new entries if applicable (if there is a language). If this is used, we could use a combination of `find` for README files and `grep` to solve my use case. I think this is simple enough.

**Comment by NewAlexandria** [comment]
I'm probably suggest outlining it as a separate Issue, and just ref this issue — so that the convo is focused.

**Comment by pdgonzalez872** [comment]
@NewAlexandria alright, closing this issue since it is solved: should add under the specific category.

As suggested, I opened a new issue about the convention idea: https://github.com/papers-we-love/papers-we-love/issues/581

Thank you
