### ISSUE TITLE
Unable to push branch to the repo. Thereby unable to create PR

### ISSUE THREAD

**Issue by amadlover** [papers-we-love/papers-we-love#593]
Hello,

Was looking to add Jerry Tessendorf's Simulating Ocean Water.pdf to the computer_graphics section.

http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.161.9102&rep=rep1&type=pdf

Thank you.
Nihal Kenkre.

**Comment by JoaoGFarias** [comment]
Did you directly clone this repo?
You would need to create a fork and only then create a PR (instructions [here](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork))

**Comment by amadlover** [comment]
Hello.

Thank you for the info.

Created pull request #594 .

Closing.

Nihal
