### ISSUE TITLE
The Development of the C Programming Language-- Change source

### ISSUE THREAD

**Issue by josh-59** [papers-we-love/papers-we-love#604]
Hello, 

Firefox throws a warning when trying to access the paper, "The Development of the C Programming Language," under "Languages/C".  I found the same paper elsewhere:

https://www.bell-labs.com/usr/dmr/www/chist.pdf

Could we change the source of this paper, in order to keep the repository clean?

**Comment by hakutsuru** [comment]
Done. Thanks @josh-59
