### ISSUE TITLE
Discussion storage

### ISSUE THREAD

**Issue by SUMUKHA-PK** [papers-we-love/papers-we-love#606]
Are the past discussions hosted somewhere?

I think it'd be a good idea for having a YouTube channel by recording the discussions :D

**Comment by DarrenN** [comment]
Hello thanks for filing an issue. Could you explain what you mean by "discussions"? I want to make sure I understand what you're asking.

Also, we do have a You Tube channel: https://www.youtube.com/user/PapersWeLove

**Comment by SUMUKHA-PK** [comment]
Thanks :)
