### ISSUE TITLE
Link to other paper-repo connected to specific directory

### ISSUE THREAD

**Issue by sukman** [papers-we-love/papers-we-love#610]
Hello!

Is it possible to add link to other paper-repo connected to specific directory and what is contributing guideline in this case?
For example, there is external ['Awesome Privacy Papers for Visual Data'](https://github.com/brighter-ai/awesome-privacy-papers) repo and it would be nice to add link to this repo in `papers-we-love/privacy/` directory.

Thank you!

**Comment by hakutsuru** [comment]
> Is it possible to add link to other paper-repo connected to specific directory

We do this in our readme (e.g. "Other Good Places to Find Papers"), so there is precedent. Links could be added there, or if the external source is mostly relevant to a topic, a similar section could be added to the directory readme.

Not sure we are ready to add this to guidelines yet, but as a first pass, I would add a new "Other Sources" section at the bottom, with a link to the repo sited. @sukman Could you create a pull request for this?

**Comment by sukman** [comment]
@hakutsuru thank you for your feedback, I created PR for this https://github.com/papers-we-love/papers-we-love/pull/613

**Comment by hakutsuru** [comment]
PR approved and merged. Thanks!
