### ISSUE TITLE
Papers We Love - Rostov-on-Don

### ISSUE THREAD

**Issue by iokasimov** [papers-we-love/papers-we-love#616]
Hello!

I'd like to to set up Papers We Love chapter in Rostov-on-Don, Russia. There are several people who like to share their favorite papers and discuss them. We have plans to host our first meetup pretty soon.

It would be nice if you create the chapter repo.

I'm Haskell developer in Rostov-on-Don.
https://twitter.com/iokasimovm

Thanks for your time, Murat.

**Comment by hakutsuru** [comment]
@iokasimov -- Rostov-on-Don is setup - https://github.com/papers-we-love/rostov-on-don

Once you accept the invitation as collaborator, please update the Readme and Code of Conduct with your chapter's information. Feel free to add other chapter organizers when appropriate.

With abuse and harassment recently in the (North American) news, we hope every new chapter will embrace our mission to foster open and accepting communities -- so please read the Code of Conduct, and let us know if it can be improved (or made more culturally aware).

Welcome aboard.
