### ISSUE TITLE
Codex

### ISSUE THREAD

**Issue by newsomc** [papers-we-love/papers-we-love#62]
This repository could provide some value by creating a codex of symbols/notation commonly used in mathematics/computer science papers. When reading a paper, I need to look up what specific symbols mean, finding that information isn't always easy. Having a codex might help ease deciphering code/examples.

I realize that symbols may take on different meaning depending on the paper. Hoping for other perspectives on this.

**Comment by DarrenN** [comment]
Any interest in this effort?

**Comment by hakutsuru** [comment]
This sounds useful, one of the joys of presentations is how equations and proofs are explained by someone who plainly explains dense notation.

Assuming a reader could decipher the material, it can be frustrating finding a relevant source for notation. Seems the best people to do this would be those who either know the material, or are working through it...

I can imagine a glossary or primer as part of the readme for various topics would be welcome, and non-controversial if kept brief and dry. Links to references in wikipedia could help, too.

**Comment by DarrenN** [comment]
I definitely agree it would be useful. Unfortunately I don't have the background in maths or logic to pull it off without lots of research. Any thoughts on who we could approach?
