### ISSUE TITLE
Video problem

### ISSUE THREAD

**Issue by itepifanio** [papers-we-love/papers-we-love#621]
The [Carmen Andoh talk about CSP](https://paperswelove.org/2018/video/carmen-andoh-on-communicating-sequential-processes/) is muted after minute 17.

**Comment by hakutsuru** [comment]
Thanks for letting us know. Unfortunately, we no longer have source video, and our mixcloud audio is also muted.

Thus, we cannot fix this problem.

@DarrenN Should we add a note about this on the website and/or youtube?

**Comment by itepifanio** [comment]
Got it, since there's nothing we can do then feel free to close this issue.
