### ISSUE TITLE
Can I host all of these papers on my website.

### ISSUE THREAD

**Issue by sultan220595** [papers-we-love/papers-we-love#667]

**Comment by hakutsuru** [comment]
That would depend on the copyright license of each paper.

While we put in the work to ensure proper hosting here (and correct mistakes), it is unreasonable for us to vouch for other uses of this copyright-restricted material.

That said, it should not take long to understand the copyright issues involved, and determine whether your distribution would violate those.

This is a github issue, so involves repo managers. For discussions of copyright, you might get more feedback on our slack (or resources like reddit). Good luck.
