### ISSUE TITLE
Setup Trivandrum Chapter

### ISSUE THREAD

**Issue by 123vivekr** [papers-we-love/papers-we-love#687]
Hi, I want to start a local chapter in **Trivandrum, India**. 

I am a CompSci grad and currently working in the software field. I'm deeply interested about research and academic papers.
Currently we are a group of 7 members and had a pre-meetup in the beginning of this month to discuss about our upcoming plans. We use Telegram for communication ([TG Group](https://t.me/+_sD5U8qT34YyNWQ1))

Here is my twitter handle = [123vivekr](https://twitter.com/123vivekr)
Thank you,
Vivek R

**Comment by hakutsuru** [comment]
@123vivekr Hi, I usually help with setting up chapters.

We could get started, but... Could you instead open this same issue in https://github.com/papers-we-love/organizers ?

This would also give you a chance to look through stuff there, and see if you have any questions. Thanks!

**Comment by 123vivekr** [comment]
Its done. Here is the [link](https://github.com/papers-we-love/organizers/issues/88).

Thank you @hakutsuru

**Comment by hakutsuru** [comment]
Thank you.
