### ISSUE TITLE
concurrency: Time, Clocks, and the Ordering of Events in a Distributed System

### ISSUE THREAD

**Issue by alexkachanov** [papers-we-love/papers-we-love#695]
Link [Time, Clocks, and the Ordering of Events in a Distributed System](http://research.microsoft.com/en-us/um/people/lamport/pubs/time-clocks.pdf) should be replaced with the direk link to Lamport's web-site: http://lamport.azurewebsites.net/pubs/pubs.html#time-clocks : http://lamport.azurewebsites.net/pubs/time-clocks.pdf

**Comment by alexkachanov** [comment]
can you add me as collaborator? I don't see in the UI how to create a branch

**Comment by xandkar** [comment]
> can you add me as collaborator? I don't see in the UI how to create a branch

You have to fork.

**Comment by alexkachanov** [comment]
done: https://github.com/papers-we-love/papers-we-love/pull/696

**Comment by hakutsuru** [comment]
Related pull request merged. Thanks.
