### ISSUE TITLE
GO Lang paper not found

### ISSUE THREAD

**Issue by varunyn** [papers-we-love/papers-we-love#704]
Repo Link - https://github.com/papers-we-love/papers-we-love/tree/master/languages/Go
Paper Link - https://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.138.6297&rep=rep1&type=pdf

**Comment by ppanero** [comment]
The DOI of the link seems to not be found: https://www.doi.org/10.1.1.138.6297

There is this https://go.dev/talks/2012/splash.article but it's not a PDF and I'm unsure if it's the actual white paper.

**Comment by DarrenN** [comment]
If you could find the correct paper and PR a fix similar to https://github.com/papers-we-love/papers-we-love/pull/709 would be much appreciated.

**Comment by ppanero** [comment]
@DarrenN I found the article, but not the PDF. I will dig a bit more at some point this week.
