### ISSUE TITLE
 Request for New Chapter Repository - Papers We Love Chapter at Manipal Institute of Technology, Bengaluru

### ISSUE THREAD

**Issue by brainst0rmer** [papers-we-love/papers-we-love#781]
Hello Papers We Love Community,

My name is Atharva Sajanikar, and I'm a second-year student studying Computer Science and Engineering at Manipal Institute of Technology, Bengaluru. I am reaching out to express my keen interest in creating a Papers We Love chapter at our institute.

About Me:
I am deeply passionate about research and fostering discussions within my college community. My goal is to create a space where students and professors from various branches can come together to explore and appreciate research papers, sparking insightful conversations and collaborative learning.

Support:
I am fortunate to have the backing of several professors who share my enthusiasm for this initiative. They are supportive of establishing a Papers We Love chapter at our institute and believe it will greatly benefit the academic atmosphere.

Team:
I have assembled a dedicated team of seven students who are equally enthusiastic about managing and promoting the chapter. Together, we aim to create an inclusive and engaging environment for everyone interested in delving into the world of research papers.

Contact Information:
Email: atharva.mitblr2022@learner.manipal.edu
LInkedIn: https://www.linkedin.com/in/atharva-sajanikar

Chapter Details:

Location: Manipal Institute of Technology, Bengaluru (https://maps.app.goo.gl/wD8zy6JeC9aKJJM66)
Starting Point: We plan to kick off the chapter with an introductory event in Jan/2024.
I kindly request the creation of a new chapter repository to facilitate our activities. Your support in establishing this chapter would mean a lot to us, and we are excited about the opportunity to contribute to the Papers We Love community.

Thank you for considering our request.

Best regards,
Atharva Sajanikar

**Comment by igalic** [comment]
maybe this repo needs more maintainers?

**Comment by DarrenN** [comment]
@brainst0rmer check your email for an invite to https://github.com/papers-we-love/bengaluru

Please follow the instructions in the default README
