### ISSUE TITLE
What is the intro music used on the 'papers we love' youtube channel?

### ISSUE THREAD

**Issue by UnchartedSystems** [papers-we-love/papers-we-love#792]
[Here's a video that includes the intro music.](https://m.youtube.com/watch?v=v_g4eZeWAng)

I've used shazam and soundhound to no avail, it's a catchy intro but I also I've heard this somewhere else.

**Comment by zeeshanlakhani** [comment]
@UnchartedSystems it was written by someone specifically for PWL: https://soundcloud.com/jessenam/popular-tracks.

**Comment by TaiTaiTai777** [comment]
The intro music used on the "Papers We Love" YouTube channel is "Cirrus (feat. Veela)" by Lensko. This information is often found mentioned in the video descriptions or credited within the video itself. If you are looking for more information about the track or licensing, you might want to look up the artist and track on platforms like YouTube or SoundCloud.
